services:
  - postgresql
  
env:
  - DB=postgres
  - DB_URL=postgres://postgres:@localhost:5432/techdatabase

language: node_js
node_js :
 - "node"
after_success: npm run test

before_script: 
   - psql -c "CREATE DATABASE techdatabase;" -U postgres 
